-- MySQL Script generated by MySQL Workbench
-- Tue May 14 21:02:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fullstackbd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fullstackbd` ;

-- -----------------------------------------------------
-- Schema fullstackbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstackbd` DEFAULT CHARACTER SET utf8mb4 ;
USE `fullstackbd` ;

-- -----------------------------------------------------
-- Table `fullstackbd`.`refugio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`refugio` (
  `id_refugio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_refugio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackbd`.`tipo_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`tipo_animal` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackbd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`usuario` (
  `idusuario` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `usuariocol` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackbd`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`perfil` (
  `dni_usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`dni_usuario`),
  CONSTRAINT `fk_perfil_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `fullstackbd`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_perfil_usuario1_idx` ON `fullstackbd`.`perfil` (`usuario_idusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `fullstackbd`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`animal` (
  `id_animal` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `id_refugio1` INT(11) NOT NULL,
  `id_tipo1` INT(11) NOT NULL,
  `img` VARCHAR(500) NOT NULL,
  `perfil_dni_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_animal`),
  CONSTRAINT `animales_ibfk_1`
    FOREIGN KEY (`id_refugio1`)
    REFERENCES `fullstackbd`.`refugio` (`id_refugio`),
  CONSTRAINT `animales_ibfk_2`
    FOREIGN KEY (`id_tipo1`)
    REFERENCES `fullstackbd`.`tipo_animal` (`id_tipo`),
  CONSTRAINT `fk_animal_perfil1`
    FOREIGN KEY (`perfil_dni_usuario`)
    REFERENCES `fullstackbd`.`perfil` (`dni_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `id_refugio1` ON `fullstackbd`.`animal` (`id_refugio1` ASC) VISIBLE;

CREATE INDEX `id_tipo1` ON `fullstackbd`.`animal` (`id_tipo1` ASC) VISIBLE;

CREATE INDEX `fk_animal_perfil1_idx` ON `fullstackbd`.`animal` (`perfil_dni_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `fullstackbd`.`donaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`donaciones` (
  `id_donacion` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_donacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `fullstackbd`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`reportes` (
  `id_reporte` INT(11) NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `dni_usuario2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reporte`),
  CONSTRAINT `reportes_ibfk_1`
    FOREIGN KEY (`dni_usuario2`)
    REFERENCES `fullstackbd`.`perfil` (`dni_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `dni_usuario2` ON `fullstackbd`.`reportes` (`dni_usuario2` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `fullstackbd`.`veterinarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackbd`.`veterinarios` (
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_refugio2` INT(11) NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `veterinarios_ibfk_1`
    FOREIGN KEY (`id_refugio2`)
    REFERENCES `fullstackbd`.`refugio` (`id_refugio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `id_refugio2` ON `fullstackbd`.`veterinarios` (`id_refugio2` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
